;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[global/wm]
; Adjust the _NET_WM_STRUT_PARTIAL top value
; Used for top aligned bars
margin-bottom = 0

; Adjust the _NET_WM_STRUT_PARTIAL bottom value
; Used for bottom aligned bars
margin-top = 0

[bar/main]
; Put the bar at the bottom of the screen
bottom = false

; Dimension defined as pixel value (e.g. 35) or percentage (e.g. 50%),
; the percentage can optionally be extended with a pixel offset like so:
; 50%:-10, this will result in a width or height of 50% minus 10 pixels
width = 100%

; Background / Foreground ARGB color
background = #00000000
foreground = #ffffff

; Under-/overline pixel size and argb color
; Individual values can be defined using:
;   {overline,underline}-size
;   {overline,underline}-color
line-size = 2
line-color =

; Number of spaces to add at the beginning/end of the bar
; Individual side values can be defined using:
;   padding-{left,right}
padding-left = 1
padding-right = 3

; Fonts are defined using <font-name>;<vertical-offset>
; Font names are specified using a fontconfig pattern.
font-0 = "UbuntuMono Nerd Font:size=12:weight=bold;2"
font-1 = "UbuntuMono Nerd Font:size=12:weight=bold;3"

; Position of the system tray window
; If empty or undefined, tray support will be disabled
; NOTE: A center aligned tray will cover center aligned modules
;
; Available positions:
;   left
;   center
;   right
;   none
tray-position = none

; Modules are added to one of the available blocks
modules-left = ewmh
modules-center = date
modules-right = xkeyboard network pulseaudio battery

; Margin (number of spaces, pixels, or points) to add before/after each module
; Individual side values can be defined using:
;   module-margin-{left,right}
module-margin = 1

; Prefer fixed center position for the `modules-center` block
; When false, the center position will be based on the size of the other blocks.
fixed-center = true

; Enable support for inter-process messaging
; See the Messaging wiki page for more details.
enable-ipc = true

[module/ewmh]
type = internal/xworkspaces

; Available tags:
format = <label-state>

; Used for the currently selected workspaces
label-active = %name%
label-active-background = #00000000
label-active-underline = #2e9ef4
label-active-padding = 1

; Used for workspaces at least one window
label-occupied = %name%
label-occupied-underline =
label-occupied-padding = 1

; Used for workspaces containing a window that is demanding attention
label-urgent = %name%
label-urgent-foreground = #000000
label-urgent-background = #ff0000
label-urgent-underline =
label-urgent-padding = 1

label-empty =

[module/date]
type = internal/date
interval = 1.0
time = "%a %b %d %I:%M %p"
format = <label>
label = %time%

[module/xkeyboard]
type = internal/xkeyboard

; Available tags:
;   <label-layout> (default)
;   <label-indicator> (default)
format = "<label-layout>"
format-spacing = 0

; Available tokens:
;   %layout%
;   %name%
;   %number%
;   %icon%
;   %variant% (New in version 3.6.0)
; Default: %layout%
label-layout = %layout%
label-layout-padding = 1

[module/network]
type = internal/network

interface-type = wireless

; Seconds to sleep between updates
; Default: 1
interval = 1

; Available tags:
;   <label-connected> (default)
;   <ramp-signal>
format-connected = "%{T2}<ramp-signal>%{T-}"

; Available tags:
;   <label-disconnected> (default)
format-disconnected = "%{T2}<label-disconnected>%{T-}"

; Default: (none)
label-disconnected = 󰤮
label-disconnected-foreground = #ffffff

; Only applies if <ramp-signal> is used
ramp-signal-0 = 󰤯 
ramp-signal-1 = 󰤥 
ramp-signal-2 = 󰤟 
ramp-signal-3 = 󰤢 
ramp-signal-4 = 󰤥 
ramp-signal-5 = 󰤨 

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/pulseaudio]
type = internal/pulseaudio

format-volume = " %{T2}<ramp-volume>%{T-}"
format-muted = " %{T2}<label-muted>%{T-}"

label-muted =  

ramp-volume-0 = 󰕿
ramp-volume-1 = 󰖀
ramp-volume-2 = 󰖀
ramp-volume-3 = 󰕾

[module/battery]
type = custom/script
exec = ~/.local/bin/battery-icon
interval = 90
tail = true
label-font = 2
format = "<label>"

[settings]
; Enables pseudo-transparency for the bar
; If set to true the bar can be transparent without a compositor.
pseudo-transparency = false

; vim:ft=cfg
